services:
  - type: web
    name: whatsapp-userbot
    env: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: Dockerfile
    buildCommand: ""        
    envVars:
      - key: PORT
        value: "10000"
