services:
  - type: web
    name: whatsapp-userbot
    env: docker
    plan: free          # ✅ Free tier
    autoDeploy: true
    dockerfilePath: Dockerfile
    buildCommand: ""    # Dockerfile handles install
    envVars:
      - key: PORT
        value: "10000"
