// plugins/hanumanchalisa.js
// Full Hanuman Chalisa plugin (Hindi + English Translation)

const chalisaHindi = [
"॥ श्री हनुमान चालीसा ॥",
"",
"श्रीगुरु चरन सरोज रज, निज मनु मुकुरु सुधारि ।",
"बरनउँ रघुबर बिमल जसु, जो दायकु फल चारि ॥",
"",
"बुद्धिहीन तनु जानिके, सुमिरौं पवन-कुमार ।",
"बल बुद्धि बिद्या देहु मोहिं, हरहु कलेस बिकार ॥",
"",
"॥ चौपाई ॥",
"जय हनुमान ज्ञान गुन सागर । जय कपीस तिहुँ लोक उजागर ॥",
"राम दूत अतुलित बल धामा । अंजनि-पुत्र पवनसुत नामा ॥",
"महाबीर बिक्रम बजरंगी । कुमति निवार सुमति के संगी ॥",
"कंचन बरन बिराज सुबेसा । कानन कुण्डल कुंचित केसा ॥",
"हाथ वज्र औ ध्वजा बिराजे । काँधे मूँज जनेउ साजे ॥",
"शंकर सुवन केसरी नंदन । तेज प्रताप महा जग बंदन ॥",
"विद्यावान गुनी अति चातुर । राम काज करिबे को आतुर ॥",
"प्रभु चरित्र सुनिबे को रसिया । राम लखन सीता मन बसिया ॥",
"सूक्ष्म रूप धरि सियहि दिखावा । बिकट रूप धरि लंक जरावा ॥",
"भीम रूप धरि असुर संहारे । रामचंद्र के काज संवारे ॥",
"लाय सजीवन लखन जियाये । श्रीरघुबीर हरषि उर लाये ॥",
"रघुपति कीन्ही बहुत बड़ाई । तुम मम प्रिय भरतहि सम भाई ॥",
"सहस बदन तुम्हरो जस गावैं । अस कहि श्रीपति कंठ लगावैं ॥",
"सनकादिक ब्रह्मादि मुनीसा । नारद सारद सहित अहीसा ॥",
"जम कुबेर दिगपाल जहाँ ते । कवि कोविद कहि सके कहाँ ते ॥",
"तुम उपकार सुग्रीवहि कीन्हा । राम मिलाय राजपद दीन्हा ॥",
"तुम्हरो मन्त्र विभीषण माना । लंकेश्वर भए सब जग जाना ॥",
"जुग सहस्त्र जोजन पर भानू । लील्यो ताहि मधुर फल जानू ॥",
"प्रभु मुद्रिका मेलि मुख माहीं । जलधि लांघि गये अचरज नाहीं ॥",
"दुर्गम काज जगत के जेते । सुगम अनुग्रह तुम्हरे तेते ॥",
"राम दुआरे तुम रखवारे । होत न आज्ञा बिनु पैसारे ॥",
"सब सुख लहै तुम्हारी सरना । तुम रक्षक काहू को डरना ॥",
"आपन तेज सम्हारो आपै । तीनों लोक हांक ते कांपै ॥",
"भूत पिशाच निकट नहिं आवै । महाबीर जब नाम सुनावै ॥",
"नासै रोग हरै सब पीरा । जपत निरंतर हनुमत बीरा ॥",
"संकट ते हनुमान छुड़ावै । मन क्रम बचन ध्यान जो लावै ॥",
"सब पर राम तपस्वी राजा । तिनके काज सकल तुम साजा ॥",
"और मनोरथ जो कोई लावै । सोई अमित जीवन फल पावै ॥",
"चारों जुग परताप तुम्हारा । है परसिद्ध जगत उजियारा ॥",
"साधु सन्त के तुम रखवारे । असुर निकंदन राम दुलारे ॥",
"अष्ट सिद्धि नौ निधि के दाता । अस बर दीन जानकी माता ॥",
"राम रसायन तुम्हरे पासा । सदा रहो रघुपति के दासा ॥",
"तुम्हरे भजन राम को पावै । जनम जनम के दुख बिसरावै ॥",
"अंतकाल रघुबर पुर जाई । जहाँ जन्म हरिभक्त कहाई ॥",
"और देवता चित्त न धरई । हनुमत सेई सर्व सुख करई ॥",
"संकट कटै मिटै सब पीरा । जो सुमिरै हनुमत बलबीरा ॥",
"जय जय जय हनुमान गोसाईं । कृपा करहु गुरु देव की नाईं ॥",
"जो सत बार पाठ कर कोई । छूटहि बंदि महा सुख होई ॥",
"जो यह पढ़ै हनुमान चालीसा । होय सिद्धि साखी गौरीसा ॥",
"तुलसीदास सदा हरि चेरा । कीजै नाथ हृदय महँ डेरा ॥",
"",
"॥ दोहा ॥",
"पवन तनय संकट हरन, मंगल मूरति रूप ।",
"राम लखन सीता सहित, हृदय बसहु सुर भूप ॥"
];

const chalisaEnglish = [
"॥ Hanuman Chalisa (English Translation) ॥",
"",
"With the dust of the Guru’s lotus feet, I cleanse the mirror of my mind.",
"I narrate the pure fame of Lord Rama, the giver of the four fruits of life.",
"",
"Knowing myself ignorant, I remember you, O Hanuman, son of the wind.",
"Grant me strength, wisdom, and knowledge, remove my miseries and defects.",
"",
"Victory to Hanuman, ocean of wisdom and virtue.",
"Victory to the chief of monkeys, who illuminates the three worlds.",
"You are the messenger of Rama, the abode of immeasurable strength,",
"Son of Anjani and known as the son of the wind.",
"You are a great hero, mighty and strong,",
"Remover of wickedness, companion of good sense.",
"Golden-complexioned, beautifully dressed,",
"With earrings and curly hair adorning you.",
"You hold the thunderbolt and the flag in your hand,",
"With sacred thread across your shoulder.",
"You are the incarnation of Lord Shiva, son of Kesari,",
"Your glory is revered by the whole world.",
"You are wise, virtuous, and clever,",
"Eager to carry out the work of Rama.",
"You delight in hearing Rama’s deeds,",
"Always dwelling in the hearts of Rama, Lakshman, and Sita.",
"You assumed a tiny form to appear before Sita,",
"And a fearsome form to burn Lanka.",
"You assumed a gigantic form to kill demons,",
"And completed the work of Lord Rama.",
"You brought the Sanjeevani herb to revive Lakshman,",
"Rama embraced you joyfully.",
"Rama praised you greatly,",
"And declared you as dear as his brother Bharata.",
"A thousand mouths sing your glory,",
"Even Lord Vishnu embraces you with love.",
"Sages, Brahma, Narad, Saraswati, and Sheshnag,",
"All sing of your virtues.",
"Yama, Kubera, and the guardians of directions,",
"Poets and scholars cannot describe your greatness.",
"You helped Sugriva,",
"By bringing him to Rama and giving him the kingdom.",
"Vibhishan followed your counsel,",
"And became the king of Lanka.",
"You swallowed the sun thinking it to be a sweet fruit,",
"Crossed the ocean with Rama’s ring in your mouth.",
"No task in the world is difficult,",
"With your grace, everything becomes easy.",
"You are the guardian of Rama’s door,",
"Without your permission none can enter.",
"All happiness is gained by serving you,",
"No one needs to fear under your protection.",
"Your roar makes the three worlds tremble,",
"Ghosts and spirits flee at your name.",
"All diseases and suffering vanish,",
"When one constantly repeats your name.",
"Hanuman frees one from troubles,",
"For those who remember him with heart, word, and deed.",
"Rama is the supreme king of ascetics,",
"And you accomplish all his tasks.",
"All desires are fulfilled by your grace,",
"Devotees enjoy the fruits of life.",
"Your glory prevails in all four ages,",
"The whole world knows of your radiance.",
"You are the protector of saints and sages,",
"And the destroyer of demons, beloved of Rama.",
"You grant the eight siddhis and nine treasures,",
"Such is the boon given by Mother Sita.",
"You have the essence of devotion to Rama,",
"And always remain his humble servant.",
"Through devotion to you, one attains Rama,",
"And all sufferings of life are removed.",
"At the end of life, one goes to Rama’s abode,",
"And is reborn as his devotee.",
"Other gods do not need to be worshipped,",
"All happiness comes from serving Hanuman.",
"All troubles vanish and sufferings end,",
"For those who remember Hanuman with strength.",
"Victory, victory, victory to you O Hanuman,",
"Please bless us as a Guru does his disciple.",
"Whoever recites this Chalisa a hundred times,",
"Is released from bondage and attains great bliss.",
"Whoever reads the Hanuman Chalisa,",
"Will achieve perfection, with Lord Shiva as witness.",
"Tulsidas is forever a servant of Hari,",
"O Lord, reside in my heart forever.",
"",
"॥ Doha ॥",
"O Son of the Wind, remover of troubles, embodiment of auspiciousness,",
"Reside forever in my heart along with Rama, Lakshman, and Sita."
];

module.exports = {
  name: "hanumanchalisa",
  command: ["hanumanchalisa", "chalisa", "hanuman"],
  description: "Get full Hanuman Chalisa in Hindi or English.",
  usage: ".chalisa [en]",
  execute: async (sock, m, args) => {
    const jid = m.key.remoteJid;
    const lang = args[0]?.toLowerCase();

    const textArray = lang === "en" ? chalisaEnglish : chalisaHindi;
    const chunkSize = 20; // WhatsApp may cut long messages, so split

    for (let i = 0; i < textArray.length; i += chunkSize) {
      const part = textArray.slice(i, i + chunkSize).join("\n");
      await sock.sendMessage(jid, { text: part }, { quoted: m });
    }
  }
};
