// dailytips.js
module.exports = {
  name: "dailytips",
  command: ["dailytips", "tip", "lifestyletips"],
  description: "Get a random daily lifestyle tip. 150+ tips included for unlimited use. Powered by SOURAV_,MD",

  async execute(sock, m, args) {
    const jid = m.key.remoteJid;

    const tips = [
      "💧 Drink at least 8 glasses of water daily.",
      "🛌 Sleep for 7-8 hours for optimal health.",
      "🥗 Eat more vegetables and fruits every day.",
      "🏃‍♂️ Take a 20-minute walk daily.",
      "🧘 Practice meditation to reduce stress.",
      "📚 Read something new every day.",
      "🌞 Get morning sunlight for vitamin D.",
      "💤 Avoid phone screens 30 minutes before sleep.",
      "🚶 Take the stairs instead of the elevator.",
      "🍎 Reduce sugar intake for better energy.",
      "📝 Write down your goals daily.",
      "💪 Exercise for at least 30 minutes.",
      "🧍‍♂️ Do a 5-minute stretch in the morning.",
      "🧼 Wash your hands frequently.",
      "🦷 Brush and floss teeth twice daily.",
      "🍵 Drink green tea for antioxidants.",
      "🖐 Practice deep breathing exercises.",
      "🎵 Listen to calming music to relax.",
      "🌿 Spend time in nature.",
      "🧘‍♀️ Try yoga at least 3 times a week.",
      "🧹 Keep your workspace clean and organized.",
      "💡 Learn a new skill monthly.",
      "🍫 Limit junk food intake.",
      "📓 Maintain a gratitude journal.",
      "🛁 Take a warm shower to relax muscles.",
      "🧑‍🤝‍🧑 Connect with friends or family daily.",
      "🎨 Engage in a creative activity weekly.",
      "📅 Plan your day the night before.",
      "📖 Read motivational quotes daily.",
      "🌬 Practice mindfulness breathing for 5 minutes.",
      "🛏 Maintain a consistent sleep schedule.",
      "💻 Take screen breaks every 60 minutes.",
      "🥛 Include calcium-rich foods in your diet.",
      "🧠 Solve puzzles to keep your brain active.",
      "🌈 Focus on positive thoughts throughout the day.",
      "🏞 Go for a short nature walk when stressed.",
      "🥤 Reduce caffeine intake after 3 PM.",
      "🎯 Set realistic and achievable goals.",
      "🖼 Surround yourself with inspiring visuals.",
      "🎁 Do a small act of kindness daily.",
      "🛋 Take short power naps if needed.",
      "🎬 Watch educational videos occasionally.",
      "🖌 Try drawing or painting as therapy.",
      "🎶 Sing or hum to improve mood.",
      "🕰 Manage time using a daily schedule.",
      "🪴 Grow indoor plants to purify air.",
      "🏃‍♀️ Stretch after exercise to avoid injury.",
      "💻 Organize digital files regularly.",
      "🗣 Practice speaking kindly to others.",
      "🚴‍♂️ Go cycling for cardio health.",
      "🎯 Focus on one task at a time.",
      "🥣 Eat breakfast within 2 hours of waking up.",
      "📅 Review your weekly achievements.",
      "🛀 Relax in a warm bath to relieve stress.",
      "💭 Practice visualization techniques.",
      "🍲 Cook your own meals for healthier eating.",
      "🧵 Try a new hobby or craft weekly.",
      "🛌 Make your bed every morning.",
      "🦵 Take short walks after meals.",
      "📖 Learn a new word daily.",
      "🎧 Listen to podcasts to expand knowledge.",
      "🪞 Look in the mirror and smile at yourself.",
      "🧴 Use sunscreen when outdoors.",
      "🏡 Keep your living area tidy.",
      "🧍‍♀️ Stand up and stretch every hour.",
      "🌟 Compliment someone daily.",
      "🗑 Declutter items you don’t need.",
      "🧩 Solve a crossword or brain teaser daily.",
      "🌱 Eat seasonal fruits and vegetables.",
      "🧘 Practice mindful eating.",
      "🛒 Make a shopping list before buying.",
      "🥗 Try a new healthy recipe weekly.",
      "🕺 Dance for fun or exercise.",
      "🎯 Set daily intentions in the morning.",
      "🍋 Drink lemon water for detox benefits.",
      "🧩 Learn a small new skill each day.",
      "🏊 Swim for full-body exercise.",
      "🗓 Review your monthly goals.",
      "🖊 Write thank-you notes or messages.",
      "🛋 Meditate for 10 minutes before bed.",
      "📚 Read 20 pages of a book daily.",
      "🧍‍♂️ Practice good posture.",
      "💡 Reflect on daily achievements.",
      "🍎 Eat slowly and mindfully.",
      "🛏 Take a short power nap if sleepy.",
      "🏃 Stretch before and after workouts.",
      "🖼 Display positive affirmations in your room.",
      "🧴 Take care of skin daily.",
      "📝 Plan meals for the week ahead.",
      "🎨 Engage in creative activities to reduce stress.",
      "🎧 Listen to motivational talks.",
      "🚶‍♀️ Walk in fresh air to refresh your mind.",
      "📖 Learn a fact about history daily.",
      "🌊 Practice deep breathing near water if possible.",
      "🥦 Include fiber in your diet.",
      "💪 Track fitness progress weekly.",
      "🧘 Do mindful meditation after waking up.",
      "🛁 Take a relaxing bath to unwind.",
      "🎯 Focus on one positive task at a time.",
      "🛌 Avoid using electronics in bed.",
      "🍇 Include antioxidants in your diet.",
      "📅 Schedule weekly personal growth activities.",
      "🪴 Water your plants daily.",
      "🧑‍🤝‍🧑 Connect meaningfully with family or friends.",
      "🏋️ Lift light weights to strengthen muscles.",
      "🕰 Take short breaks every hour during work.",
      "💧 Stay hydrated with water or herbal teas.",
      "🛌 Go to bed and wake up at the same time daily.",
      "🧘 Do yoga or stretching in the morning.",
      "🎶 Play music that lifts your mood.",
      "🍵 Take short breaks to drink tea or coffee mindfully.",
      "📝 Write a daily reflection in your journal.",
      "🖌 Engage in creative arts like drawing or painting.",
      "🏞 Spend at least 10 minutes in nature.",
      "🎯 Prioritize tasks to avoid stress.",
      "🥗 Include protein in your meals.",
      "🧠 Do mental exercises like sudoku or puzzles.",
      "🛁 Use aromatherapy to relax.",
      "🚴 Cycle or walk for cardiovascular health.",
      "🛌 Take care of proper sleep hygiene.",
      "🧘 Practice breathing exercises for focus.",
      "🌈 Reflect on what you are grateful for today.",
      "🎧 Listen to podcasts or audiobooks.",
      "🥛 Include dairy or calcium-rich foods daily.",
      "📝 Plan your day with a to-do list.",
      "🌟 Focus on positivity and avoid negative thoughts.",
      "🧍‍♀️ Move your body every hour, even for 5 minutes.",
      "🏋️ Track your workouts for motivation.",
      "🖼 Display inspirational quotes in your workspace.",
      "💤 Avoid sleeping too late to maintain health.",
      "🛀 Use relaxing rituals before bed.",
      "🎶 Play calming music while working or relaxing.",
      "🧴 Take care of personal hygiene consistently.",
      "📚 Keep learning and exploring new topics.",
      "🧩 Challenge yourself with new hobbies or games.",
      "🌿 Spend a few minutes gardening if possible.",
      "🍊 Eat a fruit of different color each day.",
      "🏃‍♂️ Start your day with a brisk walk.",
      "💭 Meditate or reflect to maintain mental clarity.",
      "🖊 Write a to-do list before sleeping.",
      "🧘‍♀️ Engage in 5–10 minutes of mindfulness.",
      "🎯 Break tasks into small achievable goals.",
      "🌞 Get sunlight exposure early in the day.",
      "🥦 Include vegetables in every meal.",
      "🛌 Make your bed every morning.",
      "🧍‍♂️ Sit up straight for good posture.",
      "💧 Drink water before meals.",
      "📖 Read a motivational quote daily.",
      "🎨 Create art for relaxation and stress relief.",
      "🛋 Take time to rest between work.",
      "🚶‍♀️ Walk after meals to aid digestion.",
      "📅 Track your personal growth weekly.",
      "🧘 Practice gratitude meditation."
    ];

    const randomTip = tips[Math.floor(Math.random() * tips.length)];

    await sock.sendMessage(jid, { text: `💡 *Daily Lifestyle Tip*\n\n${randomTip}\n\nPowered by SOURAV_,MD` }, { quoted: m });
  }
};
