// plugins/dare.js
module.exports = {
    name: "dare",
    command: ["dare"],
    info: "Get a random Dare challenge",
    execute: async (sock, m) => {
        const dares = [
            "Do 10 pushups right now!",
            "Send a voice note saying ‘I love pizza’!",
            "Text your crush ‘Hi 😊’!",
            "Sing a song and send as a voice note!",
            "Post a funny selfie on your status!",
            "Say the alphabet backward in one go.",
            "Call a random contact and say 'I miss you'.",
            "Change your WhatsApp name to ‘I am crazy’ for 1 hour.",
            "Dance for 30 seconds and send video proof!",
            "Tell the group your most embarrassing story.",
            "Put your phone on loudspeaker and read the last message aloud.",
            "Send the 5th photo in your gallery here.",
            "Pretend to be a robot for the next 5 messages.",
            "Type with your elbows for the next turn.",
            "Act like a monkey for 20 seconds (send video).",
            "Do 20 squats and send proof.",
            "Write a poem about the person to your left.",
            "Send a screenshot of your last call.",
            "Make a funny face and send a picture.",
            "Wear socks on your hands for the next 10 minutes.",
            "Send your last Google search.",
            "Speak in rhyme for the next 5 minutes.",
            "Send a random meme.",
            "Change your profile pic to something funny.",
            "Say 'I love dogs' in 5 languages.",
            "Draw something blindfolded and send pic.",
            "Send a screenshot of your home screen.",
            "Do a prank call to a friend.",
            "Record yourself laughing weirdly.",
            "Do 15 jumping jacks.",
            "Make a silly TikTok-style video.",
            "Send your oldest photo in your gallery.",
            "Act like a baby for 30 seconds.",
            "Write everyone’s name backward for 5 turns.",
            "Balance something on your head for 1 minute.",
            "Make a weird noise for 10 seconds.",
            "Do a funny dance without music.",
            "Take a spoonful of ketchup.",
            "Pretend to be a cat for 1 minute.",
            "Text someone random ‘Goodnight ❤️’.",
            "Wear your shirt backward for 10 minutes.",
            "Do your best evil laugh.",
            "Talk like a cartoon character.",
            "Try to lick your elbow.",
            "Say 'I am the best' 10 times fast.",
            "Act like a superhero.",
            "Send a silly drawing.",
            "Imitate a teacher.",
            "Do your best zombie impression.",
            "Eat something spicy and record.",
            "Send your weirdest selfie.",
            "Change your status to ‘I’m a potato’ for 1 hour.",
            "Make a weird hairstyle and send pic.",
            "Speak like a robot for 3 messages.",
            "Sing the alphabet song.",
            "Send a 5 second slow-motion video.",
            "Hop on one leg for 20 seconds.",
            "Pretend you’re a dog for 2 minutes.",
            "Send a food emoji without explanation.",
            "Say something in gibberish.",
            "Imitate a famous actor.",
            "Show your hands and feet in a photo.",
            "Do your best scary face.",
            "Act like a chef cooking imaginary food.",
            "Send your battery percentage.",
            "Talk in a whisper for 5 minutes.",
            "Send a random sticker.",
            "Pretend to cry loudly.",
            "Do your best animal sound.",
            "Spin in circles for 15 seconds.",
            "Send a ‘good morning’ to someone random.",
            "Pretend you’re an alien for 1 min.",
            "Show your funniest socks.",
            "Make a fake mustache with pen and send pic.",
            "Say ‘banana’ after every message for 5 mins.",
            "Take a selfie with your tongue out.",
            "Pretend to be Siri/Alexa.",
            "Dance with no music for 20 secs.",
            "Act like a waiter taking orders.",
            "Send a picture of your shadow.",
            "Pretend you’re a YouTuber for 30s.",
            "Talk like an old man/woman.",
            "Show your weirdest facial expression.",
            "Send a screenshot of your keyboard.",
            "Pretend to rap for 15s.",
            "Do your best karate moves.",
            "Act like a magician.",
            "Send a voice saying ‘I am a superhero’.",
            "Show your slippers/shoes pic.",
            "Make your scariest face.",
            "Pretend to be a news reporter.",
            "Send a weird emoji combo.",
            "Do your best villain laugh.",
            "Pretend you’re stuck in slow motion.",
            "Do your best opera singing.",
            "Send a 3 emoji story.",
            "Imitate a famous cartoon character."
        ];

        const dare = dares[Math.floor(Math.random() * dares.length)];
        await sock.sendMessage(m.key.remoteJid, { text: `🔥 *Dare:* ${dare}` }, { quoted: m });
    }
};
