// plugins/dare.js
const { cmd } = require('../command'); // adjust this path to your command handler

cmd({
    pattern: "dare",
    desc: "Play Dare game with 100+ random dares",
    category: "Fun",
    react: "🎲"
}, async (conn, m) => {
    try {
        // ✅ Big bank of 100+ Dares
        const dares = [
            "Send a voice note saying 'I love this group!'",
            "Change your profile picture to a funny photo for 1 hour.",
            "Sing a song and send the audio here.",
            "Text your crush 'Hi 😊' right now.",
            "Use only emojis in your next 5 messages.",
            "Post an embarrassing selfie in the group.",
            "Put your phone on your head and take a picture.",
            "Call someone and sing 'Happy Birthday' to them.",
            "Do 10 pushups and send proof.",
            "Change your bio to 'I’m a potato 🥔' for 24 hours.",
            "Send your last 5 emojis used.",
            "Speak in rhymes for the next 10 minutes.",
            "Send a funny GIF.",
            "Say the alphabet backwards in a voice note.",
            "Act like a monkey and send a video.",
            "Send a random screenshot from your gallery.",
            "Tell us your most recent Google search.",
            "Text someone 'I like pineapples 🍍' randomly.",
            "Make your status 'I’m Batman 🦇' for 1 day.",
            "Do a silly dance and record it.",
            "Imitate any member of this group in a voice note.",
            "Post your lock screen screenshot.",
            "Send your first photo in gallery.",
            "Say 'I’m the king of memes 👑' in a voice note.",
            "Send your battery percentage right now.",
            "Do 20 squats and record proof.",
            "Send a voice note saying 'I’m in love with pizza 🍕'.",
            "Use baby language in your next 5 texts.",
            "Send a random sticker spam (10 stickers).",
            "Take a selfie making a funny face.",
            "Send a screenshot of your call log.",
            "Pretend you are a news reporter and record a 15-sec clip.",
            "Send the last message you sent outside this group.",
            "Act like a robot in a voice note.",
            "Post your home screen screenshot.",
            "Confess something silly in the group.",
            "Say 'I can’t stop dancing 💃' 3 times in a voice note.",
            "Change your group nickname to 'Legend' for 1 day.",
            "Spam '😂😂😂' 15 times in the chat.",
            "Post a funny meme now.",
            "Do a prank call and record it.",
            "Send your YouTube history screenshot.",
            "Do 15 jumping jacks and send proof.",
            "Send a song lyric as your next 3 messages.",
            "Send your favorite emoji 20 times.",
            "Talk in slow motion in a voice note.",
            "Write 'I’m crazy 😂' 5 times in the chat.",
            "Record yourself whispering something random.",
            "Send a selfie with a random household item.",
            "Write a poem in the group now.",
            "Speak in an accent for the next 10 mins.",
            "Take a picture of your shoes and send it.",
            "Send a video of yourself making a funny face.",
            "Say 'Banana Banana Banana 🍌' 10 times in a voice note.",
            "Text 'I’m hungry 😭' to the last person in your DM.",
            "Draw something silly and send a photo.",
            "Change your name to 'Prankster' for 1 day.",
            "Send a screenshot of your music playlist.",
            "Do a cat impression in a voice note.",
            "Send your favorite TikTok link.",
            "Post your browsing history screenshot.",
            "Do a silly walk and record it.",
            "Pretend to cry in a voice note.",
            "Send a random contact name from your phonebook.",
            "Say 'Truth or Dare is life!' in a voice note.",
            "Change your status to '😂😂😂' for 12 hours.",
            "Spam '🤣🤣🤣' 10 times in the group.",
            "Take a selfie pretending to cry.",
            "Do 5 pushups clapping in between.",
            "Post your gallery’s 3rd picture.",
            "Send a random funny sticker.",
            "Speak like a baby in a voice note.",
            "Do a tongue twister and record it.",
            "Change your group DP to a meme for 1 day.",
            "Send your phone’s brightness screenshot.",
            "Send your favorite emoji backwards (eg: 😂😂😂 becomes 😂😂😂 reversed).",
            "Do a random TikTok challenge.",
            "Say 'I’m the boss 💪' in a voice note.",
            "Post your last sent sticker.",
            "Act like a dog barking in a voice note.",
            "Write your next 5 messages in ALL CAPS.",
            "Send the funniest pic in your phone.",
            "Post your last used WhatsApp DP.",
            "Take a selfie without smiling.",
            "Send a 10-sec random humming voice note.",
            "Send a selfie with something blue.",
            "Draw a heart and send the photo.",
            "Send the last 3 emojis you used.",
            "Say 'Truth or Dare forever' 5 times fast.",
            "Do a silly face filter photo.",
            "Record yourself laughing for 10 seconds.",
            "Send a picture of your handwriting.",
            "Pretend to be a YouTuber and send a 15-sec video.",
            "Send your most recent emoji spam.",
            "Act like an alien in a voice note.",
            "Do 10 squats and send a selfie after.",
            "Spam the word 'DARE' 10 times.",
            "Send a 5-sec singing clip.",
            "Do a random freestyle rap.",
            "Take a selfie with your left hand.",
            "Send your favorite meme now.",
            "Post a picture of your feet 😂.",
        ];

        // ✅ Pick random dare
        const randomDare = dares[Math.floor(Math.random() * dares.length)];

        // ✅ Styled output
        const replyText = `╭━❮ *🎲 DARE GAME* ❯━╮\n┣📌 *Dare:* ${randomDare}\n╰━━━━━━━━━━━━━━━╯`;

        await conn.sendMessage(m.chat, { text: replyText }, { quoted: m });

    } catch (e) {
        console.error("❌ Dare.js Error:", e);
        await conn.sendMessage(m.chat, { text: "⚠️ Something went wrong with dare command." }, { quoted: m });
    }
});
