const fs = require("fs");
const path = require("path");

module.exports = {
  name: "habit",
  command: ["habit", "habits"],
  description: "Get 5 random advanced habits at once (160+ habits)",

  async execute(sock, m, args) {
    const jid = m.key.remoteJid;

    // ====================== Habits List ======================
    const habits = [
      "Meditate daily for 20 minutes",
      "Practice gratitude journaling",
      "Read 30 pages of a book daily",
      "Write a daily reflection",
      "Plan your day every morning",
      "Limit social media usage",
      "Learn a new word daily",
      "Practice a new language",
      "Perform 10 push-ups daily",
      "Drink 2 liters of water",
      "Walk 10,000 steps",
      "Sleep 7-8 hours consistently",
      "Practice deep breathing exercises",
      "Review goals weekly",
      "Wake up before 6 AM",
      "Avoid processed sugar",
      "Track expenses daily",
      "Declutter one item daily",
      "Compliment someone daily",
      "Listen to a podcast",
      "Practice mindfulness meditation",
      "Stretch every morning",
      "No phone 1 hour before sleep",
      "Write down 3 achievements daily",
      "Check emails only twice a day",
      "Practice coding 1 hour daily",
      "Take a 5-minute cold shower",
      "Do a random act of kindness",
      "Practice visualization techniques",
      "Read news mindfully",
      "Limit caffeine intake",
      "Spend time in nature",
      "Try a new recipe weekly",
      "Journal dreams in the morning",
      "Learn a new skill weekly",
      "Reflect on mistakes daily",
      "Review finances weekly",
      "Do 15 minutes of yoga",
      "Practice positive affirmations",
      "Declutter digital space",
      "Plan meals weekly",
      "Track habits daily",
      "Volunteer once a month",
      "Unsubscribe from unnecessary emails",
      "Read a poem daily",
      "Practice creative writing",
      "Draw or sketch daily",
      "Listen to new music daily",
      "Practice a musical instrument",
      "Learn a new word in a foreign language",
      "Review your vision board",
      "Stretch after sitting 1 hour",
      "Spend 30 minutes learning online",
      "Take breaks every 90 minutes",
      "Reflect on emotional triggers",
      "Compliment yourself daily",
      "Send a thank-you note weekly",
      "Do a social media detox weekly",
      "Practice mindful eating",
      "Track calories if needed",
      "Do random exercise challenges",
      "Take cold water splash on face",
      "Read biographies",
      "Limit TV shows",
      "Track mood daily",
      "Practice hand lettering",
      "Learn calligraphy",
      "Write one blog post weekly",
      "Learn photography",
      "Watch a TED talk daily",
      "Practice shadowing foreign language",
      "Do visualization exercises",
      "Practice body scan meditation",
      "Try a new workout",
      "Avoid junk food",
      "Read self-development books",
      "Plan budget monthly",
      "Practice deep work for 2 hours",
      "Write down long-term goals",
      "Reflect on achievements monthly",
      "Check posture regularly",
      "Daily flossing",
      "Digital declutter weekly",
      "Clean workspace daily",
      "Do 5-minute journaling",
      "Learn chess tactics daily",
      "Practice memory exercises",
      "Daily gratitude message to a friend",
      "Learn typing speed exercises",
      "Watch educational videos",
      "Practice breath-hold exercises",
      "Read philosophy daily",
      "Limit sugar intake",
      "Track water intake",
      "Plan weekly adventures",
      "Do strength training",
      "Try intermittent fasting",
      "Listen to audiobooks",
      "Spend 15 minutes outdoors",
      "Learn a new app weekly",
      "Practice public speaking",
      "Daily acts of kindness",
      "Meditate before sleep",
      "Set intentions daily",
      "Visualize success",
      "Track habits in a journal",
      "Limit gossiping",
      "Focus on one task at a time",
      "Reflect on failures positively",
      "Practice patience",
      "Write one paragraph daily",
      "Learn one new software tool",
      "Do breathing exercises before stress",
      "Stretch during work breaks",
      "Reduce screen brightness at night",
      "Plan week ahead",
      "Listen actively",
      "Avoid multitasking",
      "Track mental clarity",
      "Practice gratitude before meals",
      "Reflect on conversations daily",
      "Say positive affirmations in mirror",
      "Daily walk in silence",
      "Meditate during commute",
      "Do 10 squats daily",
      "Practice mindful driving",
      "Clean one room weekly",
      "Write a letter to self",
      "Plan creative projects",
      "Track sleep patterns",
      "Practice lucid dreaming",
      "Write down one fear to overcome",
      "Daily 5-minute meditation",
      "Track productivity",
      "Daily sketching practice",
      "Try new tea/coffee",
      "Digital detox for 2 hours",
      "Read science articles",
      "Avoid procrastination triggers",
      "Set daily top 3 priorities",
      "Reflect on learning daily",
      "Practice visualization before tasks",
      "Do quick stretches every hour",
      "Learn origami",
      "Do a random good deed",
      "Practice handwriting improvement",
      "Write daily reflections",
      "Set monthly challenges",
      "Track mental health triggers",
      "Declutter email inbox",
      "Daily mindfulness exercise",
      "Practice positive self-talk",
      "Write down daily wins",
      "Daily push-up challenge",
      "Track reading progress",
      "Practice coding challenge daily",
      "Reflect on life lessons",
      "Avoid negative content online",
      "Daily journaling on emotions",
      "Practice gratitude before sleep",
      "Learn one new recipe weekly",
      "Clean workspace daily",
      "Reflect on relationships",
      "Track expenses weekly",
      "Daily meditation before work",
      "Practice silent observation",
      "Track personal growth",
      "Learn negotiation skills",
      "Daily creative expression",
      "Reflect on accomplishments",
      "Practice deep relaxation",
      "Track fitness progress",
      "Practice mindful shopping",
      "Limit TV consumption",
      "Learn something new from YouTube",
      "Daily affirmation repetition",
      "Reflect on challenges overcome",
      "Daily 10-minute yoga",
      "Write down daily intention",
      "Daily self-assessment",
      "Practice visualization at night",
      "Review achievements weekly",
      "Plan next day before sleep",
      "Daily act of kindness",
      "Track emotional wellbeing",
      "Practice mindful listening",
      "Reduce caffeine intake gradually",
      "Daily focus exercise",
      "Track long-term goals",
      "Daily learning streak",
      "Reflect on mistakes positively",
      "Daily gratitude journal",
      "Practice 5-minute meditation",
      "Track weekly wins",
      "Daily stretching",
      "Daily reading of quotes",
      "Practice patience daily",
      "Review finances monthly",
      "Set monthly goals",
      "Daily creative writing",
      "Daily reflection on day",
      "Daily language practice",
      "Daily coding challenge",
      "Weekly digital detox",
      "Daily exercise streak",
      "Daily 10 push-ups",
      "Daily meditation streak",
      "Track daily water intake",
      "Daily plan and reflect",
      "Practice new skill daily",
      "Write one new idea daily",
      "Daily journaling streak",
      "Daily mindful observation",
      "Daily gratitude exercise",
      "Daily review of tasks",
      "Daily visualization exercise"
    ];

    // ====================== Pick 5 Random Habits ======================
    const shuffled = habits.sort(() => 0.5 - Math.random());
    const selectedHabits = shuffled.slice(0, 5);
    const habitText = selectedHabits.map((h, i) => `💡 Habit ${i + 1}: ${h}`).join("\n\n");

    // ====================== Send Habits ======================
    await sock.sendMessage(jid, { text: `Here are 5 Advanced Habits for you:\n\n${habitText}` }, { quoted: m });
  },
};
