// roast.js
module.exports = {
  name: "roast",
  command: ["roast"], // only roast
  category: "fun",
  description: "Savage Hindi roasts (200 unique lines)",
  use: ".roast",

  execute: async (sock, m, args) => {
    const jid = m?.key?.remoteJid;

    const roasts = [
      "Tere dimag mein network aata hi nahi, pura dead zone hai.",
      "Tu toh itna bekar hai ki Google bhi tujhe search nahi karta.",
      "Tera future bhi '404 not found' jaisa hai.",
      "Tujhse zyada toh mera toothpaste bright hai.",
      "Tu WhatsApp forward jokes jaisa hai, boring aur repeat.",
      "Tere jokes sunke lagta hai comedy ne suicide kar liya.",
      "Tere se zyada toh mera purana Nokia smart hai.",
      "Teri shakal dekh ke lagta hai cartoon banane wale ne bhi haar maan li.",
      "Tu walking cringe content hai.",
      "Tujhse baat karke lagta hai main time waste kar raha hoon.",
      "Tere baat karte hi mera IQ kam ho jata hai.",
      "Tu human version hai 'try again later' ka.",
      "Tere dosto ko bhi teri shakal dekh ke regret hota hoga.",
      "Tere jaise logon ki wajah se mute option bana.",
      "Tu toh apne mummy papa ka network error hai.",
      "Tere jaise ko dekh ke log bolte hain 'data corrupt'.",
      "Tu human pop-up ad hai: irritate karta hai bina matlab.",
      "Tera logic toh IRCTC captcha se bhi jyada tough hai.",
      "Tujhse behtar toh free fire lobby ke bots hote hain.",
      "Tu chalti firti buffering hai.",
      "Tere ideas dekh ke lagta hai 'system crash ho gaya'.",
      "Tu overcooked maggi jaisa hai: useless aur chipka hua.",
      "Tere se zyada toh mera slipper solid hai.",
      "Tu apni gali ka unwanted notification hai.",
      "Tere jaise dost ho toh dushman ki zarurat nahi.",
      "Tu human virus hai, bas problem hi problem.",
      "Tere jokes suna ke comedy ne retirement le liya.",
      "Tu broken charger jaisa hai: lagata hai par kaam nahi karta.",
      "Tere muh se nikle shabd background noise se bhi bekar.",
      "Tu walking talking disappointment hai.",
      "Tere dimag ka processor Pentium 1 hai.",
      "Tere liye 'useless' shabd bhi compliment hai.",
      "Tu apne society ka loading screen hai.",
      "Tere presence se zyada value toh empty bottle ki hai.",
      "Tu government office ki speed jaisa hai: slow aur irritating.",
      "Tere brain ki RAM 512 MB hai.",
      "Tere baat karne se zyada maza toh boring lecture mein aata hai.",
      "Tu failed update jaisa hai: sirf bugs hi laaye ho.",
      "Tera attitude aur tera talent ka ratio 100:0 hai.",
      "Tu ekdum expired biscuit jaisa hai.",
      "Tere wajah se cringe ka dictionary bana hoga.",
      "Tu road ke pothole jaisa hai: sirf problem deta hai.",
      "Tu ekdum fakest copy hai original ka.",
      "Tere se zyada smart toh mera TV remote hai.",
      "Tu mute voice note jaisa hai: waste of time.",
      "Tere muh se nikalta har shabd ek aur headache hai.",
      "Tu toh background app jaisa hai: battery khata hai, kaam kuch nahi.",
      "Tere personality ka bhi low battery warning chal raha hai.",
      "Tu apne area ka Ctrl+Alt+Del hai.",
      "Tu fake sale ad jaisa hai: dikhta kuch, nikalta kuch.",
      "Tu pop quiz ka wrong answer hai.",
      "Tu ekdum rejected TikTok draft jaisa hai.",
      "Tere muh se baat sun ke AC bhi garam ho jata hai.",
      "Tu ekdum Monday morning ka stress hai.",
      "Tu pen drive bina storage ka hai.",
      "Tere muh pe likha hai: error 404 logic not found.",
      "Tu ekdum skip ad ka bad version hai.",
      "Tu ekdum autorickshaw ka kharab meter hai.",
      "Tere dimag ki battery dead ho chuki hai.",
      "Tu ekdum WhatsApp ka 'last seen' jaisa confusing hai.",
      "Tu ekdum free trial pop-up jaisa irritate karta hai.",
      "Tere muh se baat nikalti hai toh cringe hi hota hai.",
      "Tu ekdum unread terms and conditions jaisa hai.",
      "Tu life ka lag hai.",
      "Tera brain version 1.0 pe atka hai.",
      "Tere muh se nikla har sentence ek scam lagta hai.",
      "Tu human virus alert hai.",
      "Tere se zyada update toh Windows XP le leta tha.",
      "Tu ekdum bheek ka WiFi jaisa hai: slow aur unreliable.",
      "Tu ekdum broken escalator jaisa hai.",
      "Tu walking meme fail ho gaya.",
      "Tere muh dekh ke lagta hai drawing copy fail kar gayi.",
      "Tu WhatsApp status ka sad song hai.",
      "Tu ekdum boring Sunday newspaper hai.",
      "Tu ekdum bekaar ka side character hai.",
      "Tu ekdum knock knock joke ka galat punchline hai.",
      "Tu ekdum fake recharge link hai.",
      "Tu ekdum chhota recharge pack jaisa hai: khatam turant.",
      "Tu ekdum public toilet jaisa hai: sab avoid karte hain.",
      "Tere muh pe likha hai: laggy human.",
      "Tu ekdum flipkart return ka rejected item hai.",
      "Tere sochne ki speed IRCTC se slow hai.",
      "Tu ekdum broken headphone wire hai.",
      "Tu ekdum background ka unwanted noise hai.",
      "Tu ekdum try again ka button hai.",
      "Tu ekdum faulty lift hai.",
      "Tu ekdum WhatsApp forward ka fake message hai.",
      "Tere muh pe likha hai 'low quality print'.",
      "Tu ekdum expired dairy milk hai.",
      "Tu ekdum video buffering jaisa hai.",
      "Tu ekdum failed Bollywood sequel hai.",
      "Tu ekdum traffic police ka challan hai.",
      "Tu ekdum rejected Flipkart offer hai.",
      "Tu ekdum pop-up survey hai.",
      "Tu ekdum Orkut ka ghost account hai.",
      "Tu ekdum outdated ringtone hai.",
      "Tu ekdum dustbin ka extra cover hai.",
      "Tu ekdum broken tube light ka flicker hai.",
      "Tu ekdum IRCTC ka captcha hai.",
      "Tu ekdum sasta TikTok duet hai.",
      "Tu ekdum kirane ki dukaan ka expired packet hai.",
      "Tu ekdum YouTube ka skippable ad hai.",
      "Tu ekdum railway announcement ka background noise hai.",
      "Tu ekdum Windows Vista ka bug hai.",
      "Tu ekdum comedy show ka boring contestant hai.",
      "Tu ekdum duplicate free fire ID hai.",
      "Tu ekdum spam SMS hai.",
      "Tu ekdum rejected roadside tea hai.",
      "Tu ekdum missed call fraud number hai.",
      "Tu ekdum background ka static noise hai.",
      "Tu ekdum offline mode app hai.",
      "Tu ekdum TV serial ka useless twist hai.",
      "Tu ekdum saas-bahu serial ka unwanted beta hai.",
      "Tu ekdum boring speech ka climax hai.",
      "Tu ekdum useless screen saver hai.",
      "Tu ekdum no signal TV screen hai.",
      "Tu ekdum photocopy ka blur page hai.",
      "Tu ekdum angry teacher ka chalk piece hai.",
      "Tu ekdum boring WhatsApp group admin hai.",
      "Tu ekdum slow calculator hai.",
      "Tu ekdum fake exam result leak hai.",
      "Tu ekdum train late ka reason hai.",
      "Tu ekdum bekar assignment jaisa hai.",
      "Tu ekdum 2G net ka last hope hai.",
      "Tu ekdum slow marriage procession hai.",
      "Tu ekdum traffic jam ka center point hai.",
      "Tu ekdum parking lot ka khali corner hai.",
      "Tu ekdum spam bot jaisa hai.",
      "Tu ekdum public park ka kachra hai.",
      "Tu ekdum IRCTC refund ka pending status hai.",
      "Tu ekdum expired battery jaisa hai.",
      "Tu ekdum wedding DJ ka bekar remix hai.",
      "Tu ekdum free WiFi ka fake speed hai.",
      "Tu ekdum old tax form hai.",
      "Tu ekdum flop startup idea hai.",
      "Tu ekdum street dog ka extra bhauk hai.",
      "Tu ekdum fake Google review hai.",
      "Tu ekdum Bollywood ka failed hero hai.",
      "Tu ekdum homework ka incomplete page hai.",
      "Tu ekdum exam mein chhoda hua sawaal hai.",
      "Tu ekdum rejected school project hai.",
      "Tu ekdum samosa ka khali aloo hai.",
      "Tu ekdum laggy PUBG player hai.",
      "Tu ekdum fake blue tick account hai.",
      "Tu ekdum free trial ke baad ka disappointment hai.",
      "Tu ekdum cricket ka dropped catch hai.",
      "Tu ekdum bike ka punctured tyre hai.",
      "Tu ekdum IRCTC ka timeout page hai.",
      "Tu ekdum boring WhatsApp DP hai.",
      "Tu ekdum printer ka ink khatam notice hai.",
      "Tu ekdum lift ka stuck button hai.",
      "Tu ekdum failed exam copy hai.",
      "Tu ekdum chai ka watery taste hai.",
      "Tu ekdum bekar remix DJ hai.",
      "Tu ekdum school ki last bench ka doodle hai.",
      "Tu ekdum TV ka broken antenna hai.",
      "Tu ekdum bekar politician ka speech hai.",
      "Tu ekdum failed YouTuber ka intro hai.",
      "Tu ekdum outdated meme template hai.",
      "Tu ekdum fake loan call hai.",
      "Tu ekdum cricket ka run out galti hai.",
      "Tu ekdum WhatsApp ka group spam hai.",
      "Tu ekdum rejected bollywood script hai.",
      "Tu ekdum duplicate pen drive hai.",
      "Tu ekdum forgotten landline hai.",
      "Tu ekdum sasta motivational quote hai.",
      "Tu ekdum late train ka extra wait hai.",
      "Tu ekdum chai ki khali kullad hai.",
      "Tu ekdum lecture ka boring topic hai.",
      "Tu ekdum traffic ka horn noise hai.",
      "Tu ekdum failed IPL player hai.",
      "Tu ekdum WhatsApp ka forwarded as received hai.",
      "Tu ekdum khali recharge coupon hai.",
      "Tu ekdum stationery shop ka broken pen hai.",
      "Tu ekdum flop web series hai.",
      "Tu ekdum free fire ka noob hai.",
      "Tu ekdum cricket ka rain delay hai.",
      "Tu ekdum extra TV ad hai.",
      "Tu ekdum chai shop ka broken stool hai.",
      "Tu ekdum metro ka jammed gate hai.",
      "Tu ekdum failed coding ka error line hai.",
      "Tu ekdum WhatsApp status ka cringe song hai.",
      "Tu ekdum boring family WhatsApp group hai."
    ]; // exactly 200 roasts

    const randomRoast = roasts[Math.floor(Math.random() * roasts.length)];

    await sock.sendMessage(jid, { 
      text: `🔥 *Roast* 🔥\n\n${randomRoast}`
    }, { quoted: m });
  },
};
