// plugins/truth.js
module.exports = {
    name: "truth",
    command: ["truth"],
    info: "Get a random Truth question",
    execute: async (sock, m) => {
        const truths = [
            "What’s your biggest fear?",
            "What is the most embarrassing thing you’ve ever done?",
            "Have you ever lied to your best friend?",
            "What is your biggest regret?",
            "What secret are you keeping right now?",
            "What’s the worst thing you’ve ever said to someone?",
            "Who was your first crush?",
            "Have you ever cheated in a test?",
            "What’s the weirdest dream you’ve had?",
            "What’s the silliest thing you’re afraid of?",
            "Have you ever broken a promise?",
            "What’s the most childish thing you still do?",
            "What’s the worst gift you’ve ever received?",
            "What’s the biggest lie you’ve told your parents?",
            "What’s your guilty pleasure?",
            "Who is the last person you stalked on social media?",
            "What’s the most trouble you’ve ever gotten into at school?",
            "What’s your most awkward date experience?",
            "If you could erase one memory, what would it be?",
            "What’s the craziest excuse you’ve ever used?",
            "What’s a secret you’ve never told anyone?",
            "What’s your most embarrassing nickname?",
            "What’s the longest you’ve gone without bathing?",
            "Who do you text the most?",
            "What’s your biggest insecurity?",
            "What’s your weirdest habit?",
            "What’s the funniest thing you’ve searched online?",
            "Have you ever had a crush on a teacher?",
            "What’s your favorite guilty pleasure movie?",
            "What’s the most childish thing you still enjoy?",
            "Have you ever faked being sick?",
            "What’s the worst lie you’ve told a friend?",
            "Have you ever been caught cheating?",
            "Who do you secretly admire?",
            "What’s the strangest food you’ve eaten?",
            "What’s your worst fashion choice ever?",
            "Have you ever stolen something small?",
            "What’s a lie you tell yourself often?",
            "What’s your most embarrassing childhood memory?",
            "What’s your biggest pet peeve?",
            "What’s the dumbest reason you cried?",
            "Who was your first kiss?",
            "What’s your most useless talent?",
            "What’s the worst haircut you’ve had?",
            "Have you ever been ghosted?",
            "What’s the most awkward thing you’ve said to a crush?",
            "What’s the worst text you accidentally sent?",
            "Who’s your celebrity crush?",
            "What’s your most awkward social moment?",
            "What’s the grossest thing you’ve ever done?",
            "Have you ever been in love?",
            "What’s your worst subject in school?",
            "What’s your weirdest fear?",
            "What’s the dumbest rumor you’ve heard about yourself?",
            "What’s your favorite comfort food?",
            "Have you ever cried in public?",
            "What’s the meanest thing you’ve ever done?",
            "Who do you secretly envy?",
            "What’s the most awkward gift you’ve received?",
            "Have you ever laughed at the wrong moment?",
            "What’s your weirdest family tradition?",
            "What’s the silliest thing you’ve believed as a child?",
            "What’s your most embarrassing selfie?",
            "What’s the weirdest thing in your room?",
            "What’s your biggest turn-off?",
            "What’s the weirdest thing you’ve eaten and liked?",
            "What’s the weirdest text you’ve received?",
            "What’s the weirdest app you use?",
            "What’s the weirdest place you’ve fallen asleep?",
            "What’s your worst cooking disaster?",
            "What’s the weirdest compliment you’ve received?",
            "What’s the most embarrassing song on your playlist?",
            "What’s the worst pick-up line used on you?",
            "What’s your worst fear about the future?",
            "What’s the weirdest object you’ve kept as memory?",
            "What’s the longest you’ve gone without food?",
            "What’s your weirdest nickname?",
            "What’s your most embarrassing video?",
            "What’s your funniest childhood story?",
            "What’s the worst excuse you’ve used?",
            "What’s your most awkward school moment?",
            "What’s your worst vacation story?",
            "What’s the dumbest fight you’ve had?",
            "What’s your most awkward social media post?",
            "What’s your funniest lie?",
            "What’s your weirdest habit when alone?",
            "What’s your most embarrassing dream?",
            "What’s the weirdest thing you’ve Googled?",
            "What’s the dumbest thing you’ve done when bored?",
            "What’s the weirdest dare you’ve accepted?",
            "What’s your worst karaoke story?",
            "What’s your most awkward family story?",
            "What’s the strangest compliment you’ve given?",
            "What’s your weirdest crush?",
            "What’s the most embarrassing fall you’ve had?",
            "What’s your most awkward hairstyle?",
            "What’s your most embarrassing pet story?",
            "What’s your most awkward sleepover memory?"
        ];

        const truth = truths[Math.floor(Math.random() * truths.length)];
        await sock.sendMessage(m.key.remoteJid, { text: `🧐 *Truth:* ${truth}` }, { quoted: m });
    }
};
