// plugins/truth.js
const { cmd } = require('../command'); // adjust import if your command handler differs

cmd({
    pattern: "truth",
    desc: "Play Truth game with 100+ random truth questions",
    category: "Fun",
    react: "📝"
}, async (conn, m) => {
    try {
        // ✅ Big bank of 100+ Truth Questions
        const truths = [
            "What is the biggest lie you have ever told?",
            "Who was your first crush?",
            "Have you ever cheated in an exam?",
            "What is your most embarrassing memory?",
            "If you could date anyone in this group, who would it be?",
            "What is your secret talent?",
            "Have you ever been caught doing something you shouldn't?",
            "Who do you stalk the most on social media?",
            "Have you ever lied to your best friend?",
            "What’s the most childish thing you still do?",
            "Have you ever had a crush on a teacher?",
            "What is the dumbest thing you’ve done?",
            "What’s your guilty pleasure?",
            "What is the most awkward date you’ve been on?",
            "Have you ever faked being sick to skip school/work?",
            "What’s your most used cuss word?",
            "Have you ever stolen anything?",
            "What’s your biggest insecurity?",
            "What’s the most romantic thing you’ve done?",
            "What’s your biggest fear?",
            "What is the longest you’ve gone without showering?",
            "What’s the weirdest dream you’ve ever had?",
            "Have you ever had a paranormal experience?",
            "What is your most useless skill?",
            "What was the last lie you told?",
            "Who is your secret crush?",
            "Have you ever been friendzoned?",
            "What’s the worst gift you’ve ever received?",
            "What’s the weirdest food you’ve eaten?",
            "Have you ever peed in a pool?",
            "What’s the worst lie you’ve told your parents?",
            "Have you ever cried in public?",
            "What is your biggest regret?",
            "Who do you text the most?",
            "Have you ever had an imaginary friend?",
            "What’s your most embarrassing nickname?",
            "What’s the strangest rumor you’ve heard about yourself?",
            "What’s your favorite childhood cartoon?",
            "What’s the funniest joke you know by heart?",
            "Have you ever broken the law?",
            "Have you ever cheated in a relationship?",
            "What’s your biggest weakness?",
            "What’s something you’re glad your parents don’t know about you?",
            "Have you ever ghosted someone?",
            "What’s the worst movie you’ve ever watched?",
            "What’s your most awkward moment?",
            "What’s your weirdest habit?",
            "Have you ever been caught sneaking out?",
            "What’s the most trouble you’ve gotten into?",
            "Who is the last person you searched on social media?",
            "What’s your wildest fantasy?",
            "Have you ever been rejected by someone?",
            "What’s the most disgusting habit you have?",
            "Who is your biggest celebrity crush?",
            "What’s the most expensive thing you own?",
            "What’s your biggest turn-off?",
            "What’s your biggest turn-on?",
            "What’s your weirdest talent?",
            "What’s something you’ve never told anyone?",
            "What’s your most awkward crush?",
            "Have you ever cried over a movie?",
            "What’s the weirdest dream you’ve had recently?",
            "What’s your favorite guilty pleasure TV show?",
            "Have you ever eaten food off the floor?",
            "Have you ever had a crush on a friend’s sibling?",
            "What’s the weirdest text you’ve ever received?",
            "What’s the most embarrassing thing you’ve done drunk?",
            "What’s your worst kiss experience?",
            "What’s your worst fear?",
            "Have you ever pretended to know something you didn’t?",
            "What’s the dumbest thing you’ve said to someone you like?",
            "What’s your worst haircut ever?",
            "What’s the weirdest lie you’ve told?",
            "What’s your worst habit?",
            "What’s something you’re glad your family doesn’t know?",
            "What’s your most awkward family story?",
            "Who was your childhood crush?",
            "What’s your worst fashion choice ever?",
            "What’s the weirdest thing you’ve Googled?",
            "What’s the most embarrassing song you like?",
            "What’s your biggest bad habit?",
            "What’s something you would never tell your parents?",
            "What’s the strangest thing in your room?",
            "What’s your longest crush ever?",
            "Have you ever sent a wrong text to the wrong person?",
            "What’s the craziest dream you’ve had?",
            "What’s your weirdest school memory?",
            "Have you ever had a crush on your friend’s partner?",
            "What’s your most embarrassing social media post?",
            "What’s the dumbest thing you’ve cried about?",
            "Have you ever lied in Truth or Dare?",
            "What’s the weirdest rumor you’ve believed?",
            "What’s your favorite but embarrassing song?",
            "What’s the most awkward thing you’ve done in front of a crush?",
            "What’s your weirdest pet peeve?",
            "What’s your biggest relationship mistake?",
            "What’s your strangest hobby?",
            "What’s your favorite but embarrassing movie?",
            "What’s your weirdest school story?",
            "What’s your most embarrassing WhatsApp status ever?",
            "What’s something you’ve Googled that you regret?",
            "What’s your biggest childhood fear?",
            "What’s your most awkward school moment?",
            "What’s the weirdest food combo you’ve tried?",
            "What’s your funniest dream?",
        ];

        // ✅ Pick random truth
        const randomTruth = truths[Math.floor(Math.random() * truths.length)];

        // ✅ Styled menu-like reply
        const replyText = `╭━❮ *🤖 TRUTH GAME* ❯━╮\n┣📌 *Question:* ${randomTruth}\n╰━━━━━━━━━━━━━━━╯`;

        await conn.sendMessage(m.chat, { text: replyText }, { quoted: m });

    } catch (e) {
        console.error("❌ Truth.js Error:", e);
        await conn.sendMessage(m.chat, { text: "⚠️ Something went wrong with truth command." }, { quoted: m });
    }
});
