module.exports = {
    name: "truthdare",
    command: ["truth", "dare"],
    execute: async (sock, m, args) => {
        const truths = [
            "What is your biggest fear?",
            "Who was your first crush?",
            "What is your most embarrassing moment?",
            "Have you ever cheated on a test?",
            "What’s your secret talent?",
            "What is the worst lie you ever told?",
            "Have you ever broken someone’s trust?",
            "What is the biggest mistake of your life?",
            "Who in this group do you admire the most?",
            "What was your childhood nickname?",
            "What’s the most useless thing you’ve ever bought?",
            "Have you ever cried for no reason?",
            "What is your guilty pleasure?",
            "Have you ever stalked someone online?",
            "What is the craziest dream you’ve ever had?",
            "What is your weirdest habit?",
            "If you could erase one memory, what would it be?",
            "What is your funniest childhood memory?",
            "Have you ever lied to your parents?",
            "What’s the most embarrassing thing you’ve done in public?",
            "Have you ever skipped school without permission?",
            "Who do you secretly like?",
            "What’s the last lie you told?",
            "What’s the weirdest food you’ve eaten?",
            "What’s the scariest dream you’ve ever had?",
            "What’s your worst habit?",
            "Have you ever stolen something?",
            "What’s your favorite guilty pleasure movie?",
            "What’s the worst gift you’ve ever received?",
            "What’s your most awkward date?",
            "What’s your most childish habit?",
            "Have you ever lied to a friend?",
            "What’s your weirdest nickname?",
            "What’s your most embarrassing text you sent by mistake?",
            "What’s your biggest insecurity?",
            "What’s your strangest fear?",
            "What’s the most embarrassing thing you’ve searched online?",
            "What’s the last secret you kept from your best friend?",
            "What’s your weirdest dream ever?",
            "What’s the most trouble you’ve been in?",
            "What’s your wildest fantasy?",
            "Who do you text the most?",
            "What’s the last excuse you gave to skip something?",
            "What’s your silliest fight with a friend?",
            "What’s your worst hairstyle ever?",
            "What’s the weirdest rumor you’ve heard about yourself?",
            "What’s the last thing you Googled?",
            "What’s the funniest lie you’ve told?",
            "What’s your hidden talent?",
            "What’s your most awkward crush?",
            "What’s your worst subject in school?",
            "What’s your biggest regret?",
            "What’s the weirdest compliment you got?",
            "Who was your first celebrity crush?",
            "What’s your most embarrassing childhood photo?",
            "What’s the last lie you told your parents?",
            "What’s the most awkward thing you’ve done in front of someone you like?",
            "What’s your funniest habit?",
            "What’s the weirdest thing you’ve ever done for money?",
            "What’s your silliest fear?",
            "What’s your most embarrassing outfit?",
            "What’s the weirdest conversation you’ve had?",
            "What’s your guilty pleasure food?",
            "What’s your secret nickname?",
            "What’s your weirdest dream crush?",
            "What’s the last time you cried and why?",
            "What’s the last secret you told?",
            "What’s the weirdest dare you’ve done?",
            "What’s your most awkward hug?",
            "What’s your weirdest phone note?",
            "What’s the strangest way you’ve made money?",
            "What’s your funniest school memory?",
            "What’s your worst exam result?",
            "What’s your weirdest online purchase?",
            "What’s your strangest habit?",
            "What’s the weirdest thing in your room?",
            "What’s your most embarrassing dance move?",
            "What’s your funniest teacher memory?",
            "What’s your most awkward handshake?",
            "What’s your silliest online name?",
            "What’s the weirdest thing you’ve done alone?",
            "What’s your funniest autocorrect fail?",
            "What’s your strangest family tradition?",
            "What’s your weirdest laugh story?",
            "What’s your most awkward photo pose?",
            "What’s the weirdest pet you’ve wanted?",
            "What’s your most embarrassing ringtone?",
            "What’s the weirdest nickname you’ve given someone?",
            "What’s the funniest dare you ever did?",
            "What’s the most awkward call you made?",
            "What’s your weirdest teacher story?",
            "What’s your funniest mistake in class?",
            "What’s the most awkward selfie?",
            "What’s the weirdest dream job you had as a kid?",
            "What’s your funniest nickname story?",
            "What’s your most embarrassing fail?",
            "What’s the weirdest emoji you use?",
            "What’s your strangest morning routine?",
            "What’s your funniest sibling fight?",
            "What’s the weirdest rumor you believed?",
            "What’s your most awkward stage performance?"
        ];

        const dares = [
            "Send your last selfie right now.",
            "Sing a song and send as voice note.",
            "Send a random meme from your gallery.",
            "Change your profile pic to a funny photo for 1 hour.",
            "Say 'I love SOURAV_MD' in this group.",
            "Do 20 push-ups and send proof.",
            "Send 3 emojis that describe your crush.",
            "Call a random contact and say 'You are awesome'.",
            "Type a message without using space.",
            "Send your phone’s home screen screenshot.",
            "Eat a spoon of salt and send video proof.",
            "Change your WhatsApp status to 'I am a legend'.",
            "Send your 5th gallery photo.",
            "Record yourself saying 'I am SOURAV_MD fan' and send.",
            "Spam '😂' emoji 10 times in the chat.",
            "Tell the group your biggest secret.",
            "Post an embarrassing pic in your story.",
            "Text your crush 'I miss you'.",
            "Don’t reply in this group for 30 minutes.",
            "Dance for 30 seconds and send video.",
            "Talk in emoji for the next 5 messages.",
            "Imitate someone in the group until they guess.",
            "Send a funny voice filter audio.",
            "Send your most used emoji.",
            "Change your name to 'I am crazy' for a day.",
            "Spam the word 'YES' 20 times.",
            "Send the most recent sticker you used.",
            "Send your lockscreen screenshot.",
            "Act like a robot in a voice note.",
            "Send a mirror selfie.",
            "Do 15 squats and send proof.",
            "Send your contact list screenshot.",
            "Say a tongue twister 5 times and record it.",
            "Send your favorite meme.",
            "Send the last song you listened to.",
            "Change your wallpaper to a funny pic.",
            "Do a silly dance on video.",
            "Send a random TikTok trend video.",
            "Draw a self-portrait and send.",
            "Act like your favorite cartoon for 20 sec.",
            "Send your gallery’s oldest picture.",
            "Type backwards for your next 5 messages.",
            "Send a funny filter photo.",
            "Say 'Banana' 10 times fast and record it.",
            "Send your best smile selfie.",
            "Do a prank call and tell us.",
            "Send your favorite food picture.",
            "Sing a lullaby and record.",
            "Send a screenshot of your battery %.",
            "Tell a joke in voice note.",
            "Make a funny face selfie.",
            "Say 'I am the best' in a serious tone.",
            "Act like a baby for 10 seconds on video.",
            "Send your WhatsApp about section screenshot.",
            "Mimic a movie scene in voice note.",
            "Pretend to cry and record.",
            "Send your recent emoji history.",
            "Say 'I love group' 5 times quickly.",
            "Send a funny gif.",
            "Talk like an alien for 10 sec.",
            "Do 10 jumping jacks and record.",
            "Send your keyboard screenshot.",
            "Type only capital letters for 10 min.",
            "Send your oldest WhatsApp chat screenshot.",
            "Make a funny animal sound and send.",
            "Send your favorite emoji combo.",
            "Do a silly impression of someone.",
            "Post a funny status update.",
            "Send a screenshot of your music app.",
            "Type only numbers for 3 messages.",
            "Draw a cat and send pic.",
            "Say 'SOURAV_MD forever' 3 times.",
            "Send your gallery’s funniest pic.",
            "Record yourself laughing.",
            "Pretend to sneeze 5 times on record.",
            "Send your WhatsApp call log screenshot.",
            "Make a funny filter video.",
            "Act like a teacher for 10 sec.",
            "Do a silly walk and record.",
            "Send your favorite sticker pack.",
            "Say your name in reverse.",
            "Send your funniest voice note ever.",
            "Do a scary laugh recording.",
            "Send your favorite game screenshot.",
            "Type like a pirate for 5 min.",
            "Send a funny childhood pic.",
            "Record yourself saying 'Truth or Dare King'.",
            "Act like a news reporter for 15 sec.",
            "Send your last 3 photos in gallery.",
            "Change group dp for 1 min (if admin).",
            "Send your phone brightness screenshot.",
            "Say 'I am SOURAV fan' loudly.",
            "Send your WhatsApp storage screenshot.",
            "Act like a superhero and record.",
            "Send a random contact pic.",
            "Do 5 animal sounds.",
            "Send a screenshot of your settings.",
            "Type without using vowels for 2 lines.",
            "Send your WhatsApp backup screenshot.",
            "Make a funny rap in voice note.",
            "Act like you’re in pain and record.",
            "Send your WhatsApp chat wallpaper.",
            "Do a slow motion dance video.",
            "Say a poem in voice note.",
            "Send your funny alarm sound.",
            "Pretend to be asleep and record.",
            "Send your home screen search history.",
            "Act like your mom/dad for 20 sec.",
            "Send your funniest meme video."
        ];

        let cmd = m.body ? m.body.toLowerCase().split(" ")[0].replace(".", "") : "";

        if (cmd === "truth") {
            let truth = truths[Math.floor(Math.random() * truths.length)];
            await sock.sendMessage(
                m.key.remoteJid,
                { text: `🕵️ *Truth Question:*\n\n${truth}` },
                { quoted: m }
            );
        } else if (cmd === "dare") {
            let dare = dares[Math.floor(Math.random() * dares.length)];
            await sock.sendMessage(
                m.key.remoteJid,
                { text: `🔥 *Dare Challenge:*\n\n${dare}` },
                { quoted: m }
            );
        } else {
            await sock.sendMessage(
                m.key.remoteJid,
                { text: "❓ Use `.truth` or `.dare`" },
                { quoted: m }
            );
        }
    }
};
